from DeanerySystem.day import Day
from DeanerySystem.lesson import Lesson
from DeanerySystem.term import Term
from DeanerySystem.action import Action
from DeanerySystem.timetable import Timetable1
from DeanerySystem.teacher import Teacher
from DeanerySystem.break1 import Break
from DeanerySystem.timetable2 import Timetable2
from DeanerySystem.base_term import BaseTerm